### ISSUE TITLE
Add rails_12factor gem on heroku flag == true

### ISSUE THREAD

**Issue by namuit** [welaika/welaika-suspenders#17]
When the flag heroku is enabled, to the gemset should be added https://github.com/heroku/rails_12factor

**Comment by delphaber** [comment]
Actually rails_12factor gem has been remove from suspenders because rails 4.2(?) now uses an ENV variable by default.

https://github.com/delphaber/rails_new_blog/blob/master/config/environments/production.rb#L25

By the way `rails_stdout_logging` gem is included by suspenders

**Comment by schneems** [comment]
I think we still output a warning when rails_serve_static_assets isn't detected? The problem for old apps is if they upgraded from 3.2 to 4.0 to 4.1 to 4.2 is they won't have that config set like a new app would. The suspenders use case makes  sense but in the buildpack it's hard to detect compatability, currently we're only doing it based on gem inclusion. To get around the warning you could always add the gem to the gemfile `rails_serve_static_assets` with `require: false`

**Comment by schneems** [comment]
Btw "we" is Heroku in that comment.

**Comment by delphaber** [comment]
hi @schneems thank you. I think the `require: false`tip will be useful :)
